ChatRooms.WebApp/ViewModels/BrowseRoomViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChatRooms.WebApp.ViewModels
{
    public class BrowseRoomViewModel
    {
        public List<ChatRooms.Models.ChatRoom> Rooms { get; set; }
        public CreateRoomViewModel CreateRoom { get; set; }
    }
}

ChatRooms.WebApp/ViewModels/CreateRoomViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ChatRooms.WebApp.ViewModels
{
    public class CreateRoomViewModel
    {
        [Required]
        [MinLength(3, ErrorMessage = "Minimum lenght for room name is 3")]
        [MaxLength(15, ErrorMessage = "Please, use shorter room name")]
        public string Name { get; set; }
    }
}

ChatRooms.WebApp/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ChatRooms.WebApp.ViewModels
{
    public class LoginViewModel
    {
        [Key]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [MinLength(2, ErrorMessage = "Minimum name length is 2")]
        public string Name { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

ChatRooms.WebApp/ViewModels/RegisterView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ChatRooms.WebApp.ViewModels
{
    public class RegisterView
    {
        [Required]
        [MinLength(2, ErrorMessage = "Minimum length is 2")]
        public string Name { get; set; }

        [Required]
        [MinLength(4, ErrorMessage = "Minimum length is 4")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Compare("Password", ErrorMessage = "Password don't match")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

ChatRooms.WebApp/Controllers/AccountController.cs
using ChatRooms.Domain.Services;
using ChatRooms.Models;
using ChatRooms.WebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ChatRooms.WebApp.Controllers
{
    [AllowAnonymous]
    public class AccountController : Controller
    {
        IAccountService accountService;
        IUserService userService;
        IAuthentication auth;

        public AccountController(IAccountService accountService, IUserService userService, IAuthentication auth)
        {
            this.accountService = accountService;
            this.userService = userService;
            this.auth = auth;
        }

        // GET: Account/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: Account/Login
        [HttpPost]
        public ActionResult Login(LoginViewModel userViewModel)
        {
            var user = AutoMapper.Mapper.Map<User>(userViewModel);

            bool userIsGuest = userViewModel.Password != null ? false : true;

            user.IsGuest = userIsGuest;

            bool loginSecceded = accountService.Login(user);

            if (loginSecceded)
            {
                auth.DoAuthentication(user.Name, true);
                return RedirectToAction("Browse", "ChatRooms");
            }
            else
            {
                string errorMessage = userIsGuest ?
                    "This user already exists" :
                    "Wrong login data";

                ModelState.AddModelError("", errorMessage);
                return View("Login");
            }
        }

        // GET: Account/Logout
        public ActionResult Logout()
        {
            User user = userService.GetUserByName(User.Identity.Name);

            accountService.Logout(user);

            auth.SignOut();
            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterView newUser)
        {
            var user = AutoMapper.Mapper.Map<User>(newUser);
            userService.RegisterUser(user);
            return RedirectToAction("Browse", "ChatRooms");
        }
    }
}

ChatRooms.WebApp/Controllers/ChatRoomsController.cs
using ChatRooms.Domain.Services;
using ChatRooms.Models;
using ChatRooms.WebApp.ViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace ChatRooms.WebApp.Controllers
{
    public class ChatRoomsController : Controller
    {
        IChatRoomService chatRoomService;
        IUserService userService;

        public ChatRoomsController(IChatRoomService chatRoomService, IUserService userService)
        {
            this.chatRoomService = chatRoomService;
            this.userService = userService;
        }

        // GET: ChatRooms
        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        // GET: ChatRooms/Browse
        public ActionResult Browse()
        {
            // Get 9 most popular rooms
            List<ChatRoom> rooms = chatRoomService
                .GetAllChatRooms()
                .OrderByDescending(room => room.Users.Count)
                .Take(9)
                .ToList();

            return View(new BrowseRoomViewModel() { Rooms = rooms, CreateRoom = new CreateRoomViewModel() });
        }

        // GET: ChatRooms/Room?roomId=1
        [HttpGet]
        public ActionResult Room(int roomId)
        {
            userService.EnterRoom(roomId, User.Identity.Name);

            ChatRoom room = chatRoomService.GetRoomById(roomId);
            return View(room);
        }

        [HttpGet]
        public ActionResult Leave(string user)
        {
            userService.LeaveRoom(user);
            return RedirectToAction("Browse");
        }

        // GET: /ChatRooms/Create/
        [HttpPost]
        public ActionResult Create(CreateRoomViewModel newRoom)
        {
            bool roomExists = chatRoomService.GetRoomByName(newRoom.Name) != null;

            if (roomExists || !ModelState.IsValid)
            {
                ModelState.AddModelError("", "Sorry, this room already exists");

                ViewData["ModelIsValid"] = "false";

                List<ChatRoom> rooms = chatRoomService
                .GetAllChatRooms()
                .OrderByDescending(room => room.Users.Count)
                .Take(9)
                .ToList();

                return View("Browse", new BrowseRoomViewModel() { Rooms = rooms, CreateRoom = new CreateRoomViewModel() });
            }
            else
            {
                var room = AutoMapper.Mapper.Map<ChatRoom>(newRoom);
                room.OwnerName = User.Identity.Name;
                chatRoomService.AddRoom(room);

                return RedirectToAction("Room", "ChatRooms", new { roomId = room.ChatRoomId });
            }
        }

        public JsonResult GetAllRoomsLookup()
        {
            List<ChatRoom> rooms = chatRoomService.GetAllChatRooms();

            var list = rooms.Select(i => new { i.ChatRoomId, i.Name, rooms.Count }).ToList();

            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Help()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Kicked()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Users(int roomId)
        {
            ChatRoom room = chatRoomService.GetRoomById(roomId);
            return PartialView(room);
        }
    }
}

ChatRooms.WebApp/Controllers/LocalesController.cs
using System;
using System.Globalization;
using System.Web.Mvc;

namespace ChatRooms.WebApp.Controllers
{
    public class LocalesController : Controller
    {
        [AllowAnonymous]
        public ActionResult ChangeCulture(string lang, string returnUrl)
        {
            Session["Culture"] = new CultureInfo(lang);
            return Redirect(returnUrl);
        }
    }
}

ChatRooms.WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChatRooms.Domain.Services;
using ChatRooms.Models;

namespace ChatRooms.WebApp.Controllers
{
    public class UserController : Controller
    {
        IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }
    }
}

ChatRooms.WebApp/Views/ChatRooms/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="parallax-container">
    <div class="parallax"><img src="~/Content/images/background2.jpg" alt="background"></div>

    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h1><br /><br /></h1>
            </div>
            <div class="row center">
                <h2 class="white-text center">@Resx.SharedStrings.INFO</h2>

                <ul class="white-text right">
                    <li>
                        @Resx.SharedStrings.INFOone
                    </li>
                    <li>
                        @Resx.SharedStrings.INFOtwo
                    </li>
                    <li>
                        @Resx.SharedStrings.INFOthree
                    </li>
                </ul>
            </div>           
        </div>
    </div>
</div>


<div class="parallax-container">
    <div class="parallax"><img src="~/Content/images/sad-cat.jpg" alt="background"></div>
</div>

ChatRooms.WebApp/Views/ChatRooms/Browse.cshtml
@model ChatRooms.WebApp.ViewModels.BrowseRoomViewModel

@{
    ViewBag.Title = "Browse";
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Scripts/jquery.autocomplete.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            var response = @Html.Raw(Json.Encode(ViewData["ModelIsValid"]));

            if( response != null && response == 'false' ){
                $('#createRoomModal').openModal();
            }
        });

        $(function () {

            var rooms = [];

            var onSuccess = function (data) {
                for (var i = 0; i < data[0]['Count']; i++) {
                    rooms.push({
                        value: data[i]['Name'],
                        data: data[i]['ChatRoomId']
                    });
                }
            };

            $.ajax({
                type: 'GET',
                url: '/ChatRooms/GetAllRoomsLookup/',
                success: function (data) { onSuccess(data) },
                traditional: true
            });

            $('#autocomplete').autocomplete({
                lookup: rooms,
                onSelect: function (suggestion) {
                    window.location.href = "/ChatRooms/Room?roomId=" + suggestion.data;
                }
            });

            $('#autocomplete').blur(function () {
                $(this).val("");
            });
        });

    </script>
}

<div class="container">

    <h4 class="center-align">@Resx.SharedStrings.Find_Chat_Room</h4>
    <p class="center-align">@Resx.SharedStrings.Select_a_room_you_would_like_to_join_from_the_list_below</p>

    <div class="row room-actions-wrapper">
        <nav class="teal lighten-1">
            <div class="nav-wrapper">
                <div class="col m6 s8 room-search">
                    <form>
                        <div class="input-field" id="searchfield">
                            <input id="autocomplete" type="search" placeholder="@Resx.SharedStrings.Find_chatroom" required>
                            <label for="autocomplete"><i class="mdi-action-search"></i></label>
                            <i class="mdi-navigation-close"></i>
                        </div>
                    </form>
                </div>
                <div class="col m6 s4">
                    <ul class="right">
                        <li>
                            <a class="modal-trigger waves-effect" href="#createRoomModal">
                                <span class="hide-on-small-and-down">@Resx.SharedStrings.Create_Chatroom</span>
                                <i class="mdi-content-add right"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="row">
        <div class="rooms-wrapper">
            <div class="collection">
                @foreach (var item in Model.Rooms)
                {

                    <a href="@Url.Action("Room", "ChatRooms" , new { roomid=item.ChatRoomId } )" class="collection-item">
                        @item.Name
                        <span class="badge">@item.Users.Count</span>
                    </a>
                }
            </div>
        </div>
    </div>

    <!-- Modal Create Room -->
    <div id="createRoomModal" class="modal modal-fixed-footer">
        @Html.Partial("CreateChatRoomModalWindow", Model.CreateRoom)
    </div>
</div>

ChatRooms.WebApp/Views/ChatRooms/CreateChatRoomModalWindow.cshtml
@model ChatRooms.WebApp.ViewModels.CreateRoomViewModel

@using (Html.BeginForm("Create", "ChatRooms", FormMethod.Post))
{
    <form id="roomForm">
        <div class="modal-content">
            <h4>Create your chat room</h4>
            <div class="red-text">
                @Html.ValidationSummary(true, "")
            </div>
            <br />

            <div class="row">
                <div class="input-field col s12">
                    @Html.EditorFor(model => model.Name, new { @id = "room_name", @class = "validate" })
                    <label for="room_name">@Resx.SharedStrings.Room_name</label>
                    @Html.ValidationMessageFor(room => room.Name)
                </div>
            </div>

            <div class="row">
                <div class="col s12">
                    <b>Few small tips to know before creating your own chatroom:</b>
                </div>
                <br />
                <br />
                <div class="col s12 m4">
                    <p class="light">
                        You will need to invite people to your chatroom, otherwise it will be forever empty!
                    </p>
                </div>

                <div class="col s12 m4">
                    <p class="light">
                        As a chatroom owner you will get access to the moderator panel,
                        where you can customize your chatroom, kick or ban people and remove messages from the chat.
                    </p>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button class="modal-action btn waves-effect waves-light right" id="bnt-submit" type="submit">
                @Resx.SharedStrings.CREATE
            </button>
        </div>
    </form>
}

ChatRooms.WebApp/Views/ChatRooms/Kicked.cshtml
@{
    ViewBag.Title = "Kicked";
}


<div class="container">
    <br />
    <h2>Opps...</h2>
    <p>You was kicked for some reason.</p>
    <p>Try to be more polite next time</p>
    <a class="waves-effect waves-light btn red lighten-1" href="/ChatRooms/Browse/">Chat again</a>
</div>

ChatRooms.WebApp/Views/ChatRooms/Room.cshtml
@model ChatRooms.Models.ChatRoom

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@Model.Name</title>

    @Styles.Render("~/Content/css/material")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")

    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>

    <!--Auto-generated signaR script-->
    <script src="~/signalr/hubs"></script>

    <!-- CDN for MathJax-->
    <script type="text/javascript"
            src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">
    </script>

    <script type="text/javascript">

        jQuery.fn.extend({
            insertAtCaret: function (myValue) {
                return this.each(function (i) {
                    if (document.selection) {
                        //For browsers like Internet Explorer
                        this.focus();
                        var sel = document.selection.createRange();
                        sel.text = myValue;
                        this.focus();
                    }
                    else if (this.selectionStart || this.selectionStart == '0') {
                        //For browsers like Firefox and Webkit based
                        var startPos = this.selectionStart;
                        var endPos = this.selectionEnd;
                        var scrollTop = this.scrollTop;
                        this.value = this.value.substring(0, startPos) + myValue + this.value.substring(endPos, this.value.length);
                        this.focus();
                        this.selectionStart = startPos + myValue.length;
                        this.selectionEnd = startPos + myValue.length;
                        this.scrollTop = scrollTop;
                    } else {
                        this.value += myValue;
                        this.focus();
                    }
                });
            }
        });

        $(function () {
            // Declare a proxy to reference the hub.
            var hub = $.connection.chatHub;

            registerClientMethods(hub);

            // Start Hub
            $.connection.hub.start().done(function () {
                registerEvents(hub);
            });
        });

        function registerEvents(chatHub) {

            $('#btnSendMsg').on('click', function (e) {

                var msg = $("#txtMessage").val().trim();

                if (msg.length > 0) {
                    msg = msg.replace('\n', '<br />');
                    var userName = $("#hdUserName").val();
                    var roomName = $("#hdRoomName").val();
                    chatHub.server.send(roomName, userName, msg);
                }

                $("#txtMessage").val('');
            });

            $("#txtMessage").keydown(function (e) {
                if (e.which == 13 && e.ctrlKey) {
                    var txt = $("#txtMessage");
                    txt.val(txt.val() + "\n");
                }
            });

            $("#txtMessage").keypress(function (e) {

                if (e.which == 13) {
                    $('#btnSendMsg').click();
                }
            });

            $('#putSeparatedFormula').on('click', function (e) {
                $('#txtMessage').insertAtCaret("$$ exrp $$");
            });

            $('#putInlineFormula').on('click', function (e) {
                $('#txtMessage').insertAtCaret("\\( expr \\)");
            });

            $('a.cick_user').on("click", function (e) {
                var username = this.dataset['username'];
                var roomname = this.dataset['room'];

                chatHub.server.kickUser(username, roomname);
                $(this).parent().remove();
            });
        }

        function registerClientMethods(chatHub) {

            chatHub.client.onConnected = function (username) {
                Materialize.toast(username + ' @Resx.SharedStrings.Connected', 3000);
                $("#txtMessage").focus();

            }

            chatHub.client.userLeft = function (user) {
                Materialize.toast(user + ' left room', 3000);
            }

            chatHub.client.addNewMessageToPage = function (name, message) {
                SendMessage(name, message);

            }

            chatHub.client.userKicked = function (user) {
                Materialize.toast(user + ' was kicked', 3000);
            }


            chatHub.client.kickUser = function () {
                window.location.replace('@Url.Action("Kicked", "ChatRooms")');
            }

            chatHub.client.reloadUsers = function (room_Id) {
                $.ajax({
                    url: '@Url.Action("Users", "ChatRooms")',
                    type: 'GET',
                    cache: false,
                    data: { roomId: room_Id }
                }).done(function (result) {
                    $("#nav-mobile").html(result);
                });
            }
        }

        function SendMessage(userName, message) {
            var dt = new Date();
            var time = dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();

            $('#discussion').append(
             '<li class="collection-item avatar message">' +
                 '<i class="mdi-action-perm-identity circle"></i>' +
                 '<span class="title"><b>' + userName + '</b></span>' +
                 '<p>' + message + '</p>' +
                 '<span class="secondary-content">' + time + '</span>' +
             '</li>');

            var math = document.getElementById("discussion").lastChild;
            MathJax.Hub.Queue(["Typeset", MathJax.Hub, math]);

            var height = $('#discussion')[0].scrollHeight;
            $('#discussion').scrollTop(height);

            $("#txtMessage").focus();
        }
    </script>
</head>

<body class="room-layout">
    <nav class="white">
        <div class="nav-wrapper">

            <a class="brand-logo center black-text truncate" href="/ChatRooms/Leave?user=@User.Identity.Name"><i class="mdi-navigation-chevron-left left"></i>@Model.Name</a>

            <div class="right user-avatar hide-on-small-and-down" id="user-avatar-menu">
                <a class="dropdown-button btn-floating btn-large black" data-activates="account-menu">
                    <img src="~/Content/images/avatar.png" class="responsive-img circle">
                </a>
            </div>

            <!--User account dropdown menu-->
            <ul id="account-menu" class="dropdown-content collection with-header">
                <li class="collection-header"><h5>@User.Identity.Name</h5></li>
                <li>
                    <a href="#">
                        <span class="mdi-action-toc left menu-image"></span>
                        <span class="menu-title">@Resx.SharedStrings.Profile</span>
                    </a>
                </li>
                <li>
                    <a href="/Account/Logout">
                        <span class="mdi-action-exit-to-app left menu-image"></span>
                        <span class="menu-title">@Resx.SharedStrings.Log_out</span>
                    </a>
                </li>
            </ul>

            <!--Mobile users panel-->
            <div class="side-nav fixed room-users-wrapper" id="nav-mobile">
                @Html.Partial("Users")
            </div>

            <a href="#" data-activates="nav-mobile" class="button-collapse nav-padding"><i class="mdi-social-people black-text"></i></a>
        </div>
    </nav>
    <div class="chatroom-wrapper">
        <div>
            <ul class="collection message-wrapper" id="discussion"></ul>
        </div>

        <div class="send-wrapper">
            <div class="input-field">
                <textarea id="txtMessage" class="materialize-textarea"></textarea>
                <label for="txtMessage">@Resx.SharedStrings.Message</label>
            </div>
            <span>
                <a id="btnSendMsg"
                   class="waves-effect waves-light btn tooltipped"
                   data-position="right" data-delay="1000"
                   data-tooltip="@Resx.SharedStrings.Enter_send_message_Ctrl_Enter_new_line">
                    <i class="mdi-content-send right"></i>
                    @Resx.SharedStrings.SEND
                </a>
            </span>
            <a class="btn-floating teal lighten-1 tooltipped btn-formula" id="putInlineFormula" data-position="top" data-delay="100" data-tooltip="Inline formula">
                <i class="large mdi-editor-functions"></i>
            </a>

            <a class="btn-floating grey tooltipped btn-formula" id="putSeparatedFormula" data-position="top" data-delay="100" data-tooltip="Separated formula">
                <i class="large mdi-editor-functions"></i>
            </a>
        </div>
    </div>

    <input id="hdUserName" type="hidden" value="@User.Identity.Name" />
    <input id="hdRoomName" type="hidden" value="@Model.Name" />

</body>
</html>

ChatRooms.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css/material")
</head>

<body>
    <header>
        <div class="navbar-fixed">
            <nav class="white">
                <div class="nav-wrapper nav-padding">
                    <a class="brand-logo black-text truncate" href="/ChatRooms/Browse">&nbsp;&nbsp;&nbsp; Chat Rooms</a>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <!--Desktop navigation-->
                        <div class="right user-avatar hide-on-small-and-down" id="user-avatar-menu">
                            <a class="dropdown-button btn-floating btn-large black" data-activates="account-menu">
                                <img src="~/Content/images/avatar.png" class="responsive-img circle">
                            </a>
                        </div>

                        <ul class="right hide-on-med-and-down">
                            <li><a href="/ChatRooms/Browse" class="black-text">@Resx.SharedStrings.Rooms</a></li>
                            <li><a href="/ChatRooms/About" class="black-text">@Resx.SharedStrings.About</a></li>

                            <!--Languages dropdown-->
                            <li>
                                <a class="dropdown-button" href="#!" data-activates="language_dropdown">
                                    <i class="mdi-action-language black-text"></i>
                                </a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <div class="right hide-on-med-and-down ">
                            <a href="/Account/Register" class="waves-effect waves-indigo btn-flat">@Resx.SharedStrings.SIGN_UP</a>
                            <a href="/Account/Login" class="waves-effect waves-light btn indigo darken-2">@Resx.SharedStrings.LOGIN</a>
                        </div>

                        <ul class="right">
                            <!--Languages dropdown-->
                            <li>
                                <a class="dropdown-button" href="#!" data-activates="language_dropdown">
                                    <i class="mdi-action-language black-text"></i>
                                </a>
                            </li>
                            <li class="hide-on-med-and-down">
                                <a href="/ChatRooms/About" class="black-text">@Resx.SharedStrings.About</a>
                            </li>
                        </ul>
                    }

                    <!--User account dropdown menu-->
                    <ul id="account-menu" class="dropdown-content collection with-header">
                        <li class="collection-header"><h5>@User.Identity.Name</h5></li>
                        <li>
                            <a href="#">
                                <span class="mdi-action-toc left menu-image"></span>
                                <span class="menu-title">@Resx.SharedStrings.Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="/Account/Logout">
                                <span class="mdi-action-exit-to-app left menu-image"></span>
                                <span class="menu-title">@Resx.SharedStrings.Log_out</span>
                            </a>
                        </li>
                    </ul>

                    <!-- Language dropdown menu -->
                    <ul id="language_dropdown" class="dropdown-content">
                        <li>@Html.ActionLink("English", "ChangeCulture", "Locales", new { lang = "en", returnUrl = this.Request.RawUrl }, new { @class = "black-text" })</li>
                        <li>@Html.ActionLink("Italiano", "ChangeCulture", "Locales", new { lang = "it", returnUrl = this.Request.RawUrl }, new { @class = "black-text" })</li>
                        <li>@Html.ActionLink("Українська", "ChangeCulture", "Locales", new { lang = "uk", returnUrl = this.Request.RawUrl }, new { @class = "black-text" })</li>
                        <li>@Html.ActionLink("Русский", "ChangeCulture", "Locales", new { lang = "ru", returnUrl = this.Request.RawUrl }, new { @class = "black-text" })</li>
                    </ul>

                    <!--Mobile navigation-->
                    <div class="side-nav" id="nav-mobile">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <ul>
                                <li class="black-text active">@User.Identity.Name</li>
                                <li><a href="/ChatRooms/Browse" class="black-text">@Resx.SharedStrings.Rooms</a></li>
                                <li><a href="/ChatRooms/About" class="black-text">@Resx.SharedStrings.About</a></li>
                                <li><a href="/Account/Logout">@Resx.SharedStrings.Log_out</a></li>
                            </ul>
                        }
                        else
                        {
                            <ul>
                                <li><a href="/ChatRooms/About">@Resx.SharedStrings.About</a></li>
                            </ul>
                            <div class="row">
                                <span class="col s6"><a href="#" class="waves-effect waves-indigo btn-flat">@Resx.SharedStrings.SIGN_UP</a></span>
                                <span class="col s6"><a href="/Account/Login" class="waves-effect waves-light btn indigo darken-2 white-text">@Resx.SharedStrings.LOGIN</a></span>
                            </div>
                        }
                    </div>

                    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu black-text"></i></a>
                </div>
            </nav>
        </div>
    </header>

    <main>
        @RenderBody()
    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)
</body>
</html>